#  application-dev.yml文件内容=============================================================================
# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.195.31:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # Redis的相关配置
  data:
    redis:
      host: 192.168.195.31
      port: 6379
      password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: application-dev.yml
# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
spzx:
  minio:
    endpointUrl: http://192.168.195.31:9000
    accessKey: minio
    secreKey: 12345678
    bucketName: spzx-bucket
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode

