server:
  port: 8511

spring:
  # Redis的相关配置
  data:
    redis:
      host: 192.168.195.31
      port: 6379
      password: 123456
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.195.31:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.195.31:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml